# Generated by Django 5.0.6 on 2024-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopApp', '0005_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('phone', models.IntegerField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('zip_code', models.IntegerField(default='', max_length=5)),
                ('name_on_credit', models.CharField(max_length=70)),
                ('credit_number', models.IntegerField(default='', max_length=30)),
                ('expiry', models.DateTimeField()),
                ('CVV', models.IntegerField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='', max_length=15),
        ),
    ]
