# Generated by Django 5.0.6 on 2024-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopApp', '0011_order_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_update',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
