# Generated by Django 5.0.6 on 2024-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopApp', '0012_order_update_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
