# Generated by Django 5.0.6 on 2024-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopApp', '0013_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
