# Generated by Django 5.0.6 on 2024-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopApp', '0014_alter_order_update_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.CharField(max_length=5000),
        ),
    ]
