# Generated by Django 5.0.6 on 2024-08-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopApp', '0016_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(max_length=1000),
        ),
    ]
