# Generated by Django 5.0.6 on 2024-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('main_image', models.ImageField(default='', upload_to='static/shop')),
                ('intro_para', models.CharField(max_length=500)),
                ('heading', models.CharField(max_length=200)),
                ('para2', models.CharField(max_length=500)),
                ('image2', models.ImageField(default='', upload_to='static/shop')),
                ('para3', models.CharField(max_length=500)),
                ('image3', models.ImageField(default='', upload_to='static/shop')),
                ('conclusion', models.CharField(max_length=500)),
                ('Published_date', models.DateTimeField()),
            ],
        ),
    ]
