# Generated by Django 5.0.6 on 2024-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogApp', '0003_blogpost_list_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='list_content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
